CREATE TABLE EPISODE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	OVERALL_NUMBER INT NULL,
	SEASON_NUMBER INT NULL,
	EPISODE_NUMBER INT NULL,
	AIR_DATE DATETIME NULL,
	NAME VARCHAR(250) NULL,
	OVERVIEW VARCHAR (4000) NULL,
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY PK_EPISODE (ID)
);

CREATE TABLE `SHOW` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TVDB_ID BIGINT NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  FIRST_AIRED_DATE DATETIME NULL,
  AIR_DAY VARCHAR(50) NULL,
  AIR_TIME VARCHAR(50) NULL,

  LAST_EPISODE_ID BIGINT NULL,
  NEXT_EPISODE_ID BIGINT NULL,

  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY PK_SHOW (ID),
  FOREIGN KEY FK_EPISODE_LAST (LAST_EPISODE_ID) REFERENCES EPISODE(ID),
  FOREIGN KEY FK_EPISODE_NEXT (NEXT_EPISODE_ID) REFERENCES EPISODE(ID)

);