CREATE TABLE EPISODE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	OVERALL_NUMBER INT NULL,
	SEASON_NUMBER INT NULL,
	EPISODE_NUMBER INT NULL,
	AIR_DATE DATETIME NULL,
	NAME VARCHAR(250) NOT NULL,
	OVERVIEW VARCHAR (4000) NULL,
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY PK_EPISODE (ID)
);